cola/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
root :to => "welcome#index"

end

cola/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

cola/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

cola/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

cola/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

cola/app/helpers/application_helper.rb
module ApplicationHelper
end

cola/app/helpers/welcome_helper.rb
module WelcomeHelper
end

cola/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cola</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

  <% if current_user %>
    <%= link_to('登出', destroy_user_session_path, :method => :delete) %> |
    <%= link_to('修改密碼', edit_registration_path(:user)) %>
  <% else %>
    <%= link_to('註冊', new_registration_path(:user)) %> |
    <%= link_to('登入', new_session_path(:user)) %>
  <% end %>
</html>

cola/app/views/welcome/index.html.erb
<h1>
  HOME
</h1>